"""add_missing_fk_and_audit_columns

Revision ID: 778ea963c5a5
Revises: 58b49a92a673
Create Date: 2026-06-17 11:11:59.524193

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '778ea963c5a5'
down_revision: str | Sequence[str] | None = '58b49a92a673'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_projects', sa.Column('actor_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'deleted_projects', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_extracted_fields_file_id'), table_name='extracted_fields')
    op.add_column('operation_logs', sa.Column('actor_id', sa.String(), nullable=True))
    op.add_column('operation_logs', sa.Column('project_id', sa.String(), nullable=True))
    op.add_column('operation_logs', sa.Column('detail', sa.String(), nullable=True))
    op.drop_index(op.f('idx_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('idx_operation_logs_result'), table_name='operation_logs')
    op.create_foreign_key(None, 'operation_logs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'operation_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_parse_events_file_id'), table_name='parse_events')
    op.drop_index(op.f('idx_projects_active'), table_name='projects', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('idx_raw_files_active'), table_name='raw_files', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_raw_files_detected_type'), table_name='raw_files')
    op.drop_index(op.f('idx_raw_files_parse_status'), table_name='raw_files')
    op.drop_index(op.f('idx_raw_files_project_id'), table_name='raw_files')
    op.drop_index(op.f('idx_raw_files_project_uploaded'), table_name='raw_files')
    op.drop_index(op.f('idx_report_deliveries_actor_id'), table_name='report_deliveries')
    op.drop_index(op.f('idx_report_deliveries_kind'), table_name='report_deliveries')
    op.drop_index(op.f('idx_report_deliveries_project_created'), table_name='report_deliveries')
    op.drop_index(op.f('idx_report_deliveries_project_id'), table_name='report_deliveries')
    op.drop_index(op.f('idx_report_deliveries_section_id'), table_name='report_deliveries')
    op.drop_index(op.f('idx_report_section_meta_section_id'), table_name='report_section_meta')
    op.add_column('report_sections', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_report_sections_project_id'), table_name='report_sections')
    op.drop_index(op.f('idx_report_sections_status'), table_name='report_sections')
    op.drop_index(op.f('idx_report_versions_actor_id'), table_name='report_versions')
    op.drop_index(op.f('idx_report_versions_created'), table_name='report_versions')
    op.drop_index(op.f('idx_report_versions_project_id'), table_name='report_versions')
    op.drop_index(op.f('idx_rule_fields_template_id'), table_name='rule_fields')
    op.add_column('rule_template_versions', sa.Column('actor_id', sa.String(), nullable=True))
    op.drop_index(op.f('idx_rule_template_versions_status'), table_name='rule_template_versions')
    op.drop_index(op.f('idx_rule_template_versions_template_id'), table_name='rule_template_versions')
    op.drop_index(op.f('idx_rule_template_versions_template_time'), table_name='rule_template_versions')
    op.create_foreign_key(None, 'rule_template_versions', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_rule_templates_active'), table_name='rule_templates', postgresql_where='(deleted_at IS NULL)')
    op.add_column('system_messages', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_index(op.f('idx_system_messages_module'), table_name='system_messages')
    op.drop_index(op.f('idx_system_messages_project_id'), table_name='system_messages')
    op.drop_index(op.f('idx_system_messages_read'), table_name='system_messages')
    op.drop_index(op.f('idx_system_messages_type'), table_name='system_messages')
    op.create_foreign_key(None, 'system_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_user_preferences_current_project_id'), table_name='user_preferences')
    op.drop_index(op.f('idx_users_active'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_active'), 'users', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_user_preferences_current_project_id'), 'user_preferences', ['current_project_id'], unique=False)
    op.drop_constraint(None, 'system_messages', type_='foreignkey')
    op.create_index(op.f('idx_system_messages_type'), 'system_messages', ['type'], unique=False)
    op.create_index(op.f('idx_system_messages_read'), 'system_messages', ['read'], unique=False)
    op.create_index(op.f('idx_system_messages_project_id'), 'system_messages', ['project_id'], unique=False)
    op.create_index(op.f('idx_system_messages_module'), 'system_messages', ['module'], unique=False)
    op.drop_column('system_messages', 'user_id')
    op.create_index(op.f('idx_rule_templates_active'), 'rule_templates', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(None, 'rule_template_versions', type_='foreignkey')
    op.create_index(op.f('idx_rule_template_versions_template_time'), 'rule_template_versions', ['template_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_rule_template_versions_template_id'), 'rule_template_versions', ['template_id'], unique=False)
    op.create_index(op.f('idx_rule_template_versions_status'), 'rule_template_versions', ['status'], unique=False)
    op.drop_column('rule_template_versions', 'actor_id')
    op.create_index(op.f('idx_rule_fields_template_id'), 'rule_fields', ['template_id'], unique=False)
    op.create_index(op.f('idx_report_versions_project_id'), 'report_versions', ['project_id'], unique=False)
    op.create_index(op.f('idx_report_versions_created'), 'report_versions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_report_versions_actor_id'), 'report_versions', ['actor_id'], unique=False)
    op.create_index(op.f('idx_report_sections_status'), 'report_sections', ['status'], unique=False)
    op.create_index(op.f('idx_report_sections_project_id'), 'report_sections', ['project_id'], unique=False)
    op.drop_column('report_sections', 'deleted_at')
    op.create_index(op.f('idx_report_section_meta_section_id'), 'report_section_meta', ['section_id'], unique=False)
    op.create_index(op.f('idx_report_deliveries_section_id'), 'report_deliveries', ['section_id'], unique=False)
    op.create_index(op.f('idx_report_deliveries_project_id'), 'report_deliveries', ['project_id'], unique=False)
    op.create_index(op.f('idx_report_deliveries_project_created'), 'report_deliveries', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_report_deliveries_kind'), 'report_deliveries', ['kind'], unique=False)
    op.create_index(op.f('idx_report_deliveries_actor_id'), 'report_deliveries', ['actor_id'], unique=False)
    op.create_index(op.f('idx_raw_files_project_uploaded'), 'raw_files', ['project_id', sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index(op.f('idx_raw_files_project_id'), 'raw_files', ['project_id'], unique=False)
    op.create_index(op.f('idx_raw_files_parse_status'), 'raw_files', ['parse_status'], unique=False)
    op.create_index(op.f('idx_raw_files_detected_type'), 'raw_files', ['detected_type'], unique=False)
    op.create_index(op.f('idx_raw_files_active'), 'raw_files', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('idx_projects_active'), 'projects', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_parse_events_file_id'), 'parse_events', ['file_id'], unique=False)
    op.drop_constraint(None, 'operation_logs', type_='foreignkey')
    op.drop_constraint(None, 'operation_logs', type_='foreignkey')
    op.create_index(op.f('idx_operation_logs_result'), 'operation_logs', ['result'], unique=False)
    op.create_index(op.f('idx_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.drop_column('operation_logs', 'detail')
    op.drop_column('operation_logs', 'project_id')
    op.drop_column('operation_logs', 'actor_id')
    op.create_index(op.f('idx_extracted_fields_file_id'), 'extracted_fields', ['file_id'], unique=False)
    op.drop_constraint(None, 'deleted_projects', type_='foreignkey')
    op.drop_column('deleted_projects', 'actor_id')
    # ### end Alembic commands ###
